### ISSUE TITLE
osmo-nitb + osmo-sip-connector DTMF question

### ISSUE THREAD

**Issue by smititelu** [shamrin/osmonitb-docker#1]
Hi,

I'm using osmo-nitb + osmo-sip-connector on the BSC side and nanoBTS on the BTS side. Do you know if osmo-nitb supports DTMF and how can I enable it?

Looking at the code, I can see only some DTMF defines.

Thanks,
Stefan

**Comment by shamrin** [comment]
@smititelu I don't know. Try asking this question on OpenBSC mailing list: https://lists.osmocom.org/mailman/listinfo/openbsc

There was a very old discussion about DTMF there: http://lists.osmocom.org/pipermail/openbsc/2009-September/001917.html

I don't if there were changes since then. Ask on the mailing list.
